"use server"

import { prisma } from "@/lib/prisma"
import { getResellerSession, userHasResellerRole } from "@/lib/reseller-auth"
import {
    PLANS,
    isValidPlan,
    generateLicenseKey,
    REFUND_WINDOW_MS,
    getCreditsCost,
    tierForSpend,
    type PlanId,
    type Tier,
} from "@/lib/reseller-plans"
import { revalidatePath } from "next/cache"
import { checkLowStockAndAlert } from "@/lib/stock-alerts"

async function requireReseller() {
    const session = await getResellerSession()
    if (!session) throw new Error("Not authenticated")

    // Re-verify Discord role on every action
    const hasRole = await userHasResellerRole(session.discordId)
    if (!hasRole) throw new Error("You no longer have the reseller role.")

    const reseller = await prisma.reseller.findUnique({ where: { discordId: session.discordId } })
    if (!reseller) throw new Error("Reseller account not found.")
    if (!reseller.isActive) throw new Error("Your reseller account is suspended. Contact an admin.")

    return reseller
}

export async function generateKey(planId: string) {
    const res = await generateKeysBulk(planId, 1)
    return { key: res.keys[0], newBalance: res.newBalance }
}

/**
 * Claim N stock keys for a plan in a single atomic transaction.
 * Auto-promotes the reseller's tier if their lifetime spend crosses
 * a threshold (and they don't have manualTier set).
 */
export async function generateKeysBulk(planId: string, count: number) {
    const reseller = await requireReseller()

    if (!isValidPlan(planId)) throw new Error("Invalid plan.")
    const plan = PLANS[planId as PlanId]

    if (!Number.isInteger(count) || count <= 0) throw new Error("Count must be a positive integer.")
    if (count > 50) throw new Error("Bulk limit is 50 keys at a time.")

    const tier = (reseller.tier as Tier) || "bronze"
    const costPerKey = getCreditsCost(plan.id, tier)
    const totalCost = costPerKey * count

    if (reseller.credits < totalCost) {
        throw new Error(`Not enough credits. You need ${totalCost} but have ${reseller.credits}.`)
    }

    const result = await prisma.$transaction(async (tx) => {
        // Pull N oldest stock keys for this plan
        const stockKeys = await tx.licenseKey.findMany({
            where: {
                plan: plan.id,
                resellerId: null,
                userId: null,
                isUsed: false,
            },
            orderBy: { createdAt: "asc" },
            take: count,
        })

        if (stockKeys.length < count) {
            throw new Error(
                `Only ${stockKeys.length} ${plan.label} key${stockKeys.length === 1 ? "" : "s"} in stock. Reduce count or contact an admin to restock.`,
            )
        }

        // Claim each key
        await tx.licenseKey.updateMany({
            where: { id: { in: stockKeys.map((k: any) => k.id) } },
            data: {
                resellerId: reseller.id,
                creditsCost: costPerKey,
            },
        })

        const newBalance = reseller.credits - totalCost
        const newTotalSpent = reseller.totalSpent + totalCost

        // Determine new tier (only auto-promote if not manually set)
        const newTier = reseller.manualTier ? reseller.tier : tierForSpend(newTotalSpent)
        const promoted = newTier !== reseller.tier

        await tx.reseller.update({
            where: { id: reseller.id },
            data: {
                credits: newBalance,
                totalSpent: newTotalSpent,
                tier: newTier,
            },
        })

        const noteSuffix =
            count === 1
                ? `Claimed ${plan.label} key (${stockKeys[0].key})`
                : `Bulk-claimed ${count}× ${plan.label} keys`

        await tx.resellerLedger.create({
            data: {
                resellerId: reseller.id,
                delta: -totalCost,
                reason: "spend",
                note: noteSuffix,
                balanceAfter: newBalance,
            },
        })

        return {
            keys: stockKeys.map((k: any) => k.key),
            newBalance,
            promoted,
            newTier: newTier as Tier,
        }
    })

    revalidatePath("/reseller")
    revalidatePath("/dashboard/moderator")

    void checkLowStockAndAlert(plan.id)

    return result
}

export async function refundKey(licenseKeyId: string) {
    const reseller = await requireReseller()

    const license = await prisma.licenseKey.findUnique({ where: { id: licenseKeyId } })
    if (!license) throw new Error("Key not found.")
    if (license.resellerId !== reseller.id) throw new Error("That key wasn't generated by you.")
    if (license.isUsed || license.usedCount > 0) throw new Error("This key has already been redeemed and can't be refunded.")

    const ageMs = Date.now() - license.createdAt.getTime()
    if (ageMs > REFUND_WINDOW_MS) {
        throw new Error("Refund window has expired (1 hour).")
    }

    const refundAmount = license.creditsCost
    const newBalance = reseller.credits + refundAmount

    await prisma.$transaction(async (tx) => {
        await tx.licenseKey.delete({ where: { id: licenseKeyId } })

        await tx.reseller.update({
            where: { id: reseller.id },
            data: {
                credits: newBalance,
                totalSpent: Math.max(0, reseller.totalSpent - refundAmount),
            },
        })

        await tx.resellerLedger.create({
            data: {
                resellerId: reseller.id,
                delta: refundAmount,
                reason: "refund",
                note: `Refund for ${license.plan} key (${license.key})`,
                balanceAfter: newBalance,
            },
        })
    })

    revalidatePath("/reseller")
    return { success: true, newBalance }
}
